trigger:
  - master

pool:
  vmImage: $(imageName)

jobs:

- job: Swift_latest
  strategy:
    matrix:
      Ubuntu 20.04:
        imageName: ubuntu-20.04
      Ubuntu 18.04:
        imageName: ubuntu-18.04
      Ubuntu 16.04:
        imageName: ubuntu-16.04
  pool:
    vmImage: $(imageName)
  # We currently can't use the official Swift Docker image, because it no longer comes with with zlib dependency
  container: norionomura/swift:latest
  steps:
    - script: swift test -c release -Xswiftc -enable-testing
      displayName: Linux Swift latest

- job: Linux_Swift_5_0
  strategy:
    matrix:
      Ubuntu 20.04:
        imageName: ubuntu-20.04
      Ubuntu 18.04:
        imageName: ubuntu-18.04
      Ubuntu 16.04:
        imageName: ubuntu-16.04
  pool:
    vmImage: $(imageName)
  # We currently can't use the official Swift Docker image, because it no longer comes with with zlib dependency
  container: norionomura/swift:5.0.0
  steps:
    - script: swift test -c release -Xswiftc -enable-testing
      displayName: Linux Swift 5.0

- job: Linux_Swift_4_2
  strategy:
    matrix:
      Ubuntu 20.04:
        imageName: ubuntu-20.04
      Ubuntu 18.04:
        imageName: ubuntu-18.04
      Ubuntu 16.04:
        imageName: ubuntu-16.04
  pool:
    vmImage: $(imageName)
  container: swift:4.2
  steps:
    - script: swift test -c release -Xswiftc -enable-testing
      displayName: Linux Swift 4.2

- job: Linux_Swift_4_1
  strategy:
    matrix:
      Ubuntu 20.04:
        imageName: ubuntu-20.04
      Ubuntu 18.04:
        imageName: ubuntu-18.04
      Ubuntu 16.04:
        imageName: ubuntu-16.04
  pool:
    vmImage: $(imageName)
  container: swift:4.1
  steps:
    - script: swift test -c release -Xswiftc -enable-testing
      displayName: Linux Swift 4.1

- job: Linux_Swift_4_0
  strategy:
    matrix:
      Ubuntu 20.04:
        imageName: ubuntu-20.04
      Ubuntu 18.04:
        imageName: ubuntu-18.04
      Ubuntu 16.04:
        imageName: ubuntu-16.04
  pool:
    vmImage: $(imageName)
  container: swift:4.0
  steps:
    - script: swift test -c release -Xswiftc -enable-testing
      displayName: Linux Swift 4.0

- job: macOS_latest
  pool:
    vmImage: macOS-latest
  steps:
    - task: Xcode@5
      inputs:
        actions: 'test'
        packageApp: false
        exportMethod: 'development'
        exportOptionsPlist: ''
        configuration: 'Release'
        scheme: 'ZIPFoundation'
        sdk: 'macosx'
        destinationPlatformOption: 'macOS'
        useXcpretty: true
        publishJUnitResults: true
    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: build/reports/**
        failTaskOnFailedTests: true

- job: macOS_10_14
  pool:
    vmImage: macOS-10.14
  steps:
    - task: Xcode@5
      inputs:
        actions: 'test'
        packageApp: false
        exportMethod: 'development'
        exportOptionsPlist: ''
        configuration: 'Release'
        scheme: 'ZIPFoundation'
        sdk: 'macosx'
        destinationPlatformOption: 'macOS'
        useXcpretty: true
        publishJUnitResults: true
    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: build/reports/**
        failTaskOnFailedTests: true



- job: iOS_latest
  pool:
    vmImage: macOS-latest
  steps:
    - task: Xcode@5
      inputs:
        actions: 'test'
        packageApp: false
        exportMethod: 'development'
        exportOptionsPlist: ''
        configuration: 'Release'
        scheme: 'ZIPFoundation'
        sdk: 'iphonesimulator'
        destinationPlatformOption: 'iOS'
        destinationTypeOption: 'simulators'
        destinationSimulators: 'iPhone 11'
        useXcpretty: true
        publishJUnitResults: true
    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: build/reports/**
        failTaskOnFailedTests: true

- job: watchOS_5_1
  pool:
    vmImage: macOS-latest
  steps:
    # We currently only perform a build-only script for watchOS (xcodebuild test is unable to find the XCTest module)
    - task: Xcode@5
      inputs:
        actions: 'build'
        packageApp: false
        exportMethod: 'development'
        exportOptionsPlist: ''
        configuration: 'Release'
        scheme: 'ZIPFoundation'
        sdk: 'watchsimulator'
        destinationPlatformOption: 'custom'
        destinationTypeOption: 'simulators'
        destinationSimulators: 'Apple Watch Series 3 - 38mm'

- job: tvOS_latest
  pool:
    vmImage: macOS-latest
  steps:
    - task: Xcode@5
      inputs:
        actions: 'test'
        packageApp: false
        exportMethod: 'development'
        exportOptionsPlist: ''
        configuration: 'Release'
        scheme: 'ZIPFoundation'
        sdk: 'appletvsimulator'
        destinationPlatformOption: 'tvOS'
        destinationTypeOption: 'simulators'
        destinationSimulators: 'Apple TV 4K'
        useXcpretty: true
        publishJUnitResults: true
    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: build/reports/**
        failTaskOnFailedTests: true

- job: SwiftLint
  pool:
    vmImage: macOS-latest
  steps:
    - script: xcodebuild -scheme ZIPFoundation clean build-for-testing > xcodebuild.log
      displayName: Generate xcodebuild.log
    - script: HOMEBREW_NO_AUTO_UPDATE=1 brew install https://raw.github.com/Homebrew/homebrew-core/master/Formula/swiftlint.rb
      displayName: Install SwiftLint
    - script: |
        set -o pipefail
        mkdir -p build/reports/
        swiftlint lint --reporter junit > build/reports/swiftlint.xml
      displayName: SwiftLint
    - task: PublishTestResults@2
      inputs:
        testRunner: JUnit
        testResultsFiles: build/reports/**
        failTaskOnFailedTests: true
    - script: swiftlint analyze --strict --compiler-log-path xcodebuild.log
      displayName: SwiftLint Analyze

- job: CodeCoverage
  pool:
    vmImage: macOS-latest
  steps:
    - script: xcodebuild test -destination 'platform=macOS,arch=x86_64' -scheme "ZIPFoundation" -derivedDataPath Build/ 
      displayName: Generate xccovreport
    - script: (xcrun xccov view --only-targets --report Build/Logs/Test/*.xcresult | grep -Eq  "ZIPFoundation.*100\.00%") && { exit 0; } || { echo '##vso[task.logissue type=error;]Please make sure that the test suite covers all framework code paths.'; exit 1; }
      displayName: Check for full line coverage
